### ISSUE TITLE
Unable to update from version: 2.23.0 to Latest version: 2.25.0. - QNAP NAS

### ISSUE THREAD

**Issue by AlphaOmega2020** [theotherp/nzbhydra2#604]
* What do you expect to happen? Expected to upgrade from 2.23.0 to 2.25.0.
* What does happen? it just hangs
* Have you searched for this problem? I have.
* Can the problem be reproduced? Click "update now"

[nzbhydra-debuginfos-2020-08-03-20-33.zip](https://github.com/theotherp/nzbhydra2/files/5018080/nzbhydra-debuginfos-2020-08-03-20-33.zip)

=====================

[~] # 2020-08-03 19:11:34.761  INFO --- [http-nio-0.0.0.0-5] org.nzbhydra.update.UpdateManager        : [Host: .local] Starting process to update to v2.25.0
2020-08-03 19:11:46.514  INFO --- [http-nio-0.0.0.0-5] org.nzbhydra.backup.BackupAndRestore     : [Host: .local] Deleting old backups if any exist
2020-08-03 19:11:46.538  INFO --- [http-nio-0.0.0.0-5] org.nzbhydra.backup.BackupAndRestore     : [Host: .local] Creating backup
2020-08-03 19:11:46.577  INFO --- [http-nio-0.0.0.0-5] org.nzbhydra.backup.BackupAndRestore     : [Host: .local] Successfully wrote backup to file /share/CACHEDEV1_DATA/.qpkg/NZBHydra2/data/backup/nzbhydra-2020-08-03 19-11-46.zip
2020-08-03 19:11:46.891  INFO --- [          Thread-5] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2020-08-03 19:11:47.368  WARN --- [          Thread-5] .s.c.a.CommonAnnotationBeanPostProcessor : Destroy method on bean with name 'nzbHydra' threw an exception: org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'searcher': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)
        at java.awt.TrayIcon.<clinit>(TrayIcon.java:120)
        at java.lang.Thread.run(Thread.java:748)

========================================

[~] # 2020-08-03 19:15:55.399  INFO --- [http-nio-0.0.0.0-5] org.nzbhydra.update.UpdateManager        : [Host: .local] Starting process to update to v2.25.0
2020-08-03 19:16:08.036  INFO --- [http-nio-0.0.0.0-5] org.nzbhydra.backup.BackupAndRestore     : [Host: .local] Deleting old backups if any exist
2020-08-03 19:16:08.040  INFO --- [http-nio-0.0.0.0-5] org.nzbhydra.backup.BackupAndRestore     : [Host: .local] Backing up database to /share/CACHEDEV1_DATA/.qpkg/NZBHydra2/data/backup/nzbhydra-2020-08-03 19-16-08.zip
2020-08-03 19:16:08.089  INFO --- [http-nio-0.0.0.0-5] org.nzbhydra.update.UpdateManager        : [Host: .local] Shutting down to let wrapper execute the update
2020-08-03 19:16:08.828  INFO --- [          Thread-5] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
2020-08-03 19:16:08.838  INFO --- [http-nio-0.0.0.0-5] org.nzbhydra.config.BaseConfig           : [Host: .local] Using data folder /share/CACHEDEV1_DATA/.qpkg/NZBHydra2/data
2020-08-03 19:16:08.995  INFO --- [http-nio-0.0.0.0-5] o.n.d.downloaders.DownloaderProvider     : [Host: .local] Initializing downloader SABnzbd
2020-08-03 19:16:09.131  INFO --- [http-nio-0.0.0.0-5] com.zaxxer.hikari.HikariDataSource       : [Host: .local] HikariPool-2 - Start completed.
2020-08-03 19:16:09.144  INFO --- [http-nio-0.0.0.0-5] o.f.core.internal.command.DbValidate     : [Host: .local] Successfully validated 26 migrations (execution time 00:00.010s)
2020-08-03 19:16:09.157  INFO --- [http-nio-0.0.0.0-5] o.f.core.internal.command.DbMigrate      : [Host: .local] Schema "PUBLIC" is up to date. No migration necessary.

        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:603)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:307)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1862)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$ShortcutDependencyDescriptor.resolveShortcut(AutowiredAnnotationBeanPostProcessor.java:791)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1207)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:603)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$ShortcutDependencyDescriptor.resolveShortcut(AutowiredAnnotationBeanPostProcessor.java:791)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1207)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.access$000(AutowiredAnnotationBeanPostProcessor.java:131)
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:116)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1429)
        at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveInnerBean(BeanDefinitionValueResolver.java:389)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1706)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$ShortcutDependencyDescriptor.resolveShortcut(AutowiredAnnotationBeanPostProcessor.java:791)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1207)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.access$000(AutowiredAnnotationBeanPostProcessor.java:131)
        at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:342)
        at org.springframework.beans.factory.support.ConstructorResolver.resolveConstructorArguments(ConstructorResolver.java:680)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1338)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557)
        at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveInnerBean(BeanDefinitionValueResolver.java:374)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1706)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:645)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1338)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
        at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:330)
        at org.springframework.beans.factory.support.ConstructorResolver.resolveConstructorArguments(ConstructorResolver.java:680)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1338)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:625)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:113)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:498)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:603)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
        at org.springframework.boot.autoconfigure.AutoConfigurationPackages.get(AutoConfigurationPackages.java:74)
        at org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration.getPackagesToScan(JpaBaseConfiguration.java:153)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
        at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:342)
        at org.springframework.beans.factory.support.ConstructorResolver.resolvePreparedArguments(ConstructorResolver.java:824)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1358)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
        at org.springframework.aop.framework.autoproxy.BeanFactoryAdvisorRetrievalHelper.findAdvisorBeans(BeanFactoryAdvisorRetrievalHelper.java:91)
        at org.springframework.aop.framework.autoproxy.AbstractAdvisorAutoProxyCreator.findEligibleAdvisors(AbstractAdvisorAutoProxyCreator.java:94)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:603)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:400)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanDefinition(DefaultListableBeanFactory.java:805)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:297)
        at org.springframework.context.annotation.ConfigurationClassPostProcessor$ImportAwareBeanPostProcessor.postProcessBeforeInitialization(ConfigurationClassPostProcessor.java:462)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1795)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1338)
2020-08-03 19:16:09.204  INFO --- [http-nio-0.0.0.0-5] o.n.d.downloaders.DownloaderProvider     : [Host: .local] Finished initializing active downloaders
Exception in thread "Thread-5" java.lang.NoClassDefFoundError: Could not initialize class java.awt.Toolkit
        at org.nzbhydra.update.UpdateManager.lambda$exitWithReturnCode$8(UpdateManager.java:414)

===============================================

[~] # 2020-08-03 19:19:43.330  INFO --- [http-nio-0.0.0.0-5] org.nzbhydra.update.UpdateManager        : [Host: .local] Starting process to update to v2.25.0
2020-08-03 19:19:54.538  INFO --- [http-nio-0.0.0.0-5] org.nzbhydra.backup.BackupAndRestore     : [Host: .local] Deleting old backups if any exist
2020-08-03 19:19:54.540  INFO --- [http-nio-0.0.0.0-5] org.nzbhydra.backup.BackupAndRestore     : [Host: .local] Backing up database to /share/CACHEDEV1_DATA/.qpkg/NZBHydra2/data/backup/nzbhydra-2020-08-03 19-19-54.zip
2020-08-03 19:19:54.578  INFO --- [http-nio-0.0.0.0-5] org.nzbhydra.update.UpdateManager        : [Host: .local] Shutting down to let wrapper execute the update
2020-08-03 19:19:55.848  INFO --- [          Thread-5] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
Exception in thread "Thread-5" java.lang.NoClassDefFoundError: Could not initialize class java.awt.Toolkit
        at org.nzbhydra.update.UpdateManager.lambda$exitWithReturnCode$8(UpdateManager.java:414)

===============================================

[~] # 2020-08-03 19:21:34.692  INFO --- [http-nio-0.0.0.0-5] org.nzbhydra.update.UpdateManager        : [Host: .local] Starting process to update to v2.25.0
2020-08-03 19:21:47.482  INFO --- [http-nio-0.0.0.0-5] org.nzbhydra.backup.BackupAndRestore     : [Host: .local] Deleting old backups if any exist
2020-08-03 19:21:47.484  INFO --- [http-nio-0.0.0.0-5] org.nzbhydra.backup.BackupAndRestore     : [Host: .local] Backing up database to /share/CACHEDEV1_DATA/.qpkg/NZBHydra2/data/backup/nzbhydra-2020-08-03 19-21-47.zip
2020-08-03 19:21:47.762  INFO --- [http-nio-0.0.0.0-5] org.nzbhydra.update.UpdateManager        : [Host: .local] Shutting down to let wrapper execute the update
2020-08-03 19:21:48.550  INFO --- [          Thread-5] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
Exception in thread "Thread-5" java.lang.NoClassDefFoundError: Could not initialize class java.awt.Toolkit
        at org.nzbhydra.update.UpdateManager.lambda$exitWithReturnCode$8(UpdateManager.java:414)

===============================================

[~] # 2020-08-03 19:23:24.720  INFO --- [http-nio-0.0.0.0-5] org.nzbhydra.update.UpdateManager        : [Host: .local] Starting process to update to v2.25.0
2020-08-03 19:23:36.484  INFO --- [http-nio-0.0.0.0-5] org.nzbhydra.backup.BackupAndRestore     : [Host: .local] Deleting old backups if any exist
2020-08-03 19:23:36.487  INFO --- [http-nio-0.0.0.0-5] org.nzbhydra.backup.BackupAndRestore     : [Host: .local] Backing up database to /share/CACHEDEV1_DATA/.qpkg/NZBHydra2/data/backup/nzbhydra-2020-08-03 19-23-36.zip
2020-08-03 19:23:36.542  INFO --- [http-nio-0.0.0.0-5] org.nzbhydra.update.UpdateManager        : [Host: .local] Shutting down to let wrapper execute the update
2020-08-03 19:23:37.158  INFO --- [          Thread-5] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
Exception in thread "Thread-5" java.lang.NoClassDefFoundError: Could not initialize class java.awt.Toolkit
        at org.nzbhydra.update.UpdateManager.lambda$exitWithReturnCode$8(UpdateManager.java:414)

**Comment by theotherp** [comment]
Not sure how QNAP works but you can just update by shutting down hydra and replacing the file in the `lib` folder with the one from [the latest release](https://github.com/theotherp/nzbhydra2/releases/download/v2.25.0/nzbhydra2-2.25.0-linux.zip).

**Comment by AlphaOmega2020** [comment]
I tried that but it fails to load with nzbhydra2wrapperPy3.py:

ERROR - Main process shut down unexpectedly. If the wrapper was started in daemon mode you might not see the error output. Start Hydra manually with the same parameters in the same environment to see it

works fine with 2.23.

**Comment by theotherp** [comment]
Check the wrapper log

**Comment by AlphaOmega2020** [comment]
I replaced the entire file system Excluding the data folder and all is fine now, thanks.
