### ISSUE TITLE
Unable to shutdown or restart via UI on linux

### ISSUE THREAD

**Issue by digglor** [theotherp/nzbhydra2#31]
When trying to shutdown or restart i receive the following exception on linux. The process stays active.

2018-01-07 15:54:01.570  WARN --- [       Thread-6] .s.c.a.CommonAnnotationBeanPostProcessor : Invocation of destroy method failed on bean with name 'nzbHydra': java.lang.NoClassDefFoundError: Could not initialize class java.awt.Toolkit
Exception in thread "Thread-6" java.lang.NoClassDefFoundError: Could not initialize class org.nzbhydra.WindowsTrayIcon
        at org.nzbhydra.update.UpdateManager.lambda$exitWithReturnCode$3(UpdateManager.java:291)
        at java.lang.Thread.run(Thread.java:748)

**Comment by mason-xx** [comment]
Can't confirm, working fine on ubuntu 17.10, Hydra running as a systemd service...

**Comment by theotherp** [comment]
It's quite possible that this depends on the system it runs on . I know how
to fix it even if I can't reproduce it.

Am 07.01.2018 5:31 nachm. schrieb "mason-xx" <notifications@github.com>:

**Comment by digglor** [comment]
I'm running it on Linux qnap 4.2.8 #1 SMP Sat Dec 30 06:01:19 CST 2017 x86_64 GNU/Linux and using a custom start/stop script that launches ./nzbhydra2 2>&1 &
